language: android

notifications:
  email: false

sudo: false

android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-26.0.2
    - android-26

before_install:
  - chmod +x gradlew

script:
  - ./gradlew assembleRelease